### ISSUE TITLE
Error finding solution.xml file path

### ISSUE THREAD

**Issue by SpiralIT** [devkeydet/dyn365-ce-devops#49]
Hi,
I am seeing the following failure when the MSCRM pack solution is running:
[error]Cannot find path 'D:\a\1\s\SolutionPackage\package\Other\Solution.xml' because it does not exist.

How is it resolving the file path to D:\a\1\s - do I need to update a variable or config file?

I get this error referencing CrmAsyncRequestResponseSample projects.

Thanks
Andy

**Comment by WaelHamze** [comment]
There is a property on the task that you need to set to the root folder where your extracted customisations are stored in source control.

**Comment by SpiralIT** [comment]
Thanks that's all working now.
Andy
